version: "3.8"
services:
  app:
    environment:
      - DEBUG_MODE=true
  db:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
  redis:
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
  smtp:
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host

