version: "3.8"
services:
  db:
    image: postgres:15
    secrets:
      - pq_password
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=orders
      - POSTGRES_PASSWORD_FILE=/run/secrets/pq_password
    networks:
      - orders-api

  app:
    image: final:1.1
    command: run-app runserver 0.0.0.0:8000
    secrets:
     - pq_password
    environment:
      - PQ_PASSWORD=/run/secrets/pq_password
      - PQ_USER=postgres_user
      - PQ_DB_NAME=orders
      - PQ_HOST=db
      - PQ_PORT=5432
    ports:
      - target: 8000
        published: 80
    networks:
      - orders-api

networks:
  orders-api:
    name: orders-api

secrets:
  pq_password:
    file: ./pq_password.txt
